apiVersion: v1
kind: Service
metadata:
  name: analytics-api
  namespace: bank-dwh
  labels:
    app: analytics-api
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: analytics-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  namespace: bank-dwh
  labels:
    app: analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-api
  template:
    metadata:
      labels:
        app: analytics-api
    spec:
      containers:
        - name: api
          image: bank_dwh_analytics_api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: CLICKHOUSE_HTTP_PORT
              value: "8123"
            - name: CLICKHOUSE_USER
              value: default
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bank-dwh-secrets
                  key: clickhouse-password
            - name: CLICKHOUSE_DATABASE
              value: bank_marts
            - name: ANALYTICS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-dwh-secrets
                  key: analytics-api-key
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
