apiVersion: v1
kind: Secret
metadata:
  name: bank-dwh-secrets
  namespace: bank-dwh
type: Opaque
stringData:
  postgres-password: "dwh_secret"
  grafana-admin-password: "admin"
  airflow-www-password: "airflow"
  airflow-fernet-key: "Mm6O6AKe_GZsPjpqeYoRwTsXUexcivZbudj331sWXps="
  airflow-webserver-secret-key: "airflow_dev_secret_change_me"
  analytics-api-key: ""
  postgres-exporter-dwh-dsn: "postgresql://dwh:dwh_secret@postgres:5432/bank_dwh?sslmode=disable"
  postgres-exporter-airflow-dsn: "postgresql://dwh:dwh_secret@postgres:5432/airflow?sslmode=disable"
  airflow-metadata-conn: "postgresql+psycopg2://dwh:dwh_secret@postgres:5432/airflow"
  dwh-database-url: "postgresql://dwh:dwh_secret@postgres:5432/bank_dwh"
  clickhouse-password: "ch_dwh_secret"
